apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sample-app2
  namespace: sample-app
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sample-app
      version: "0.1.2"
      sourceRef:
        kind: GitRepository
        name: sample-app-helm-chart
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: nginx
      tag: "1.25.2"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    env:
      - name: ENVIRONMENT
        value: "production"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
# ...add more values as needed for your chart...